# Generated by Django 4.1.5 on 2023-03-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0002_savat_umumiy'),
    ]

    operations = [
        migrations.AddField(
            model_name='savat',
            name='miqdor',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
