# Generated by Django 4.1.5 on 2023-03-08 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
        ('userapp', '0002_izoh'),
    ]

    operations = [
        migrations.AddField(
            model_name='izoh',
            name='mahsulot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asosiy.mahsulot'),
        ),
    ]
